#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for MCP Server Integration Feature
# Spec: 002-research-and-plan-mcp-integration-architecture

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Change to project root
cd "$(dirname "$0")/../../.."
PROJECT_ROOT=$(pwd)

echo "Project root: $PROJECT_ROOT"
echo ""

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start within ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo "Installing dependencies..."
pnpm install

# ============================================
# BUILD SHARED TYPES (required by other services)
# ============================================

echo ""
echo "Building shared types library..."
cd "$PROJECT_ROOT/libs/types"
npm run build
cd "$PROJECT_ROOT"

# ============================================
# START BACKEND SERVER
# ============================================

echo ""
echo "Starting backend server..."
cd "$PROJECT_ROOT/apps/server"
npm run dev &
BACKEND_PID=$!
cd "$PROJECT_ROOT"

# Wait for backend
wait_for_service 3000 "Backend Server"

# ============================================
# START FRONTEND UI
# ============================================

echo ""
echo "Starting frontend UI..."
cd "$PROJECT_ROOT/apps/ui"
npm run dev &
FRONTEND_PID=$!
cd "$PROJECT_ROOT"

# Wait for frontend (Vite uses port 5173 by default)
wait_for_service 5173 "Frontend UI"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:3000"
echo "  Frontend UI:  http://localhost:5173"
echo ""
echo "Key Pages for MCP Feature:"
echo "  Settings:     http://localhost:5173/settings"
echo "  Kanban Board: http://localhost:5173/"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running and handle termination
trap "echo 'Stopping services...'; kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; exit 0" SIGINT SIGTERM

# Wait for background processes
wait
